default_install_hook_types:
  - pre-commit
  - pre-merge-commit
default_stages:
  - pre-commit
  - pre-merge-commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: '\.snap$'
      - id: mixed-line-ending
        args: [--fix=auto]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: "3.0.3"
    hooks:
      - id: editorconfig-checker
        alias: ec
  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.26
    hooks:
      - id: actionlint
        # Disable shellcheck and pyflakes
        args: ["-shellcheck=", "-pyflakes="]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.3
    hooks:
      - id: ruff
        files: \.py$
        args: [
            --fix,
            --exit-non-zero-on-fix,
            "--select",
            "I,E1,E4,E7,E9,F,UP,N",
          ] # sort imports and fix (rules taken from nf-core/tools)
      - id: ruff-format # formatter
