name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update APT and Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl python3 python3-pip make

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: List directory contents
      run: ls -R

    - name: Install Python Dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install .[dev]

    - name: Validate pyproject.toml
      run: |
        python3 -m pip install toml
        python3 -c "import toml; toml.load('pyproject.toml')"

    - name: Run Tests
      run: make test
