name: Publish Python Package

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Extract version from __init__.py and update pyproject.toml
        run: |
          VERSION=$(grep '__version__ = ' src/bayescurvefit/__init__.py | sed 's/.*"\(.*\)".*/\1/')
          sed -i "s/version = \".*\"/version = \"$VERSION\"/" pyproject.toml

      - name: Install dependencies
        run: uv sync --dev

      - name: Build package
        run: uv build

      - name: Publish to PyPI
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          uv run twine upload --username __token__ --password $PYPI_API_TOKEN dist/*
